CREATE TABLE TELEFONO (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    CITY_CODE VARCHAR(255),
    CONTRY_CODE VARCHAR(255),
    NUMBER VARCHAR(255)
);

CREATE TABLE USUARIO (
    ID UUID PRIMARY KEY,
    IS_ACTIVE BOOLEAN NOT NULL,
    CREATED TIMESTAMP,
    LAST_LOGIN TIMESTAMP,
    MODIFIED TIMESTAMP,
    EMAIL VARCHAR(255) UNIQUE,
    NAME VARCHAR(255),
    PASSWORD VARCHAR(255),
    TOKEN VARCHAR(255)
);

CREATE TABLE USUARIO_TELEFONOS (
    TELEFONOS_ID BIGINT NOT NULL,
    USUARIO_ID UUID NOT NULL,
    CONSTRAINT UNIQUE_TELEFONOS_ID UNIQUE (TELEFONOS_ID),
    FOREIGN KEY (USUARIO_ID) REFERENCES USUARIO(ID),
    FOREIGN KEY (TELEFONOS_ID) REFERENCES TELEFONO(ID)
);